version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  nginx:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
  api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
     - 3333:3333
     - 3000:3000

